--ALİAS
SELECT U.USERNAME_ KULLANICIADI,
U.NAMESURNAME AS ADSOYAD,
U.EMAIL AS EMAIL,
U.TELNR1 TELEFON1,
U.TELNR2 TELEFON2,
C.CITY AS SEHİR,
T.TOWN AS ILCE,
D.DISTRICT MAHALLE,
A.ADDRESSTEXT ADRES
FROM USER_ U --TAKMA İSİM ALİAS
LEFT JOIN ADDRES A ON U.ID=A.USERID
LEFT JOIN CITY C ON C.ID=A.CITYID
LEFT JOIN TOWN T ON T.ID=A.TOWNID
LEFT JOIN DISTRICT D ON D.ID=A.DISTRICTID
WHERE U.ID=15