--SELECT * 
--FROM [ETRADE].dbo.SALES

--SELECT * FROM SALES WHERE BRANCH='Kocaeli Subesi'
--SELECT SUM(LINENET) AS TOPLAMSATIS ,COUNT(*) AS SATIRSAYISI ,
--MIN(LINENET) AS ENDUSUKFIYAT,MAX(LINENET) AS ENYUKSEKFIYAT ,AVG(LINENET) AS ORTALAMASATISFIYATI
--FROM SALES WHERE BRANCH='KOCAELİ Subesi'

--SELECT 
--BRANCH,
--SUM(LINENET) AS TOPLAMSATIS ,COUNT(*) AS SATIRSAYISI ,
--MIN(LINENET) AS ENDUSUKFIYAT,MAX(LINENET) AS ENYUKSEKFIYAT ,AVG(LINENET) AS ORTALAMASATISFIYATI
--FROM SALES 
--GROUP BY BRANCH 

--SELECT  BRANCH AS SUBEADI,SUM(LINENET) AS TOPLAMSATIS
--FROM SALES
--GROUP BY BRANCH ORDER BY 2 

-- *** TOPLAM SATIS 50.000' DEN FAZLA OLAN MAĞAZALAR

--SELECT BRANCH AS SUBEADI, SUM(LINENET) AS TOPLAMSATIS
--FROM SALES
--GROUP BY BRANCH 
--HAVING SUM(LINENET)>50000 --WHERE SARTI İLE OLMUYOR
--ORDER BY 2 DESC

--BİR MAĞAZANIN GÜN BAZLI SATIŞ RAKAMLARI
--SELECT BRANCH AS SUBE,DATE_ TARİH,SUM(LINENET) TOPLAMSATIS, COUNT(BRANCH) SATIRSAYISI
--FROM SALES 
--WHERE BRANCH='HATAY SUBESİ'--AND DATE_='2017-01-05'--
--GROUP BY BRANCH,DATE_ ORDER BY BRANCH,DATE_

--SELECT * FROM SALES WHERE BRANCH= 'ANKARA SUBESİ' ORDER BY DATE_

--BİR GÜNÜN MAĞAZA BAZLI SATIŞ RAKAMLARI
--SELECT DATE_,BRANCH,SUM(LINENET) FROM SALES
--WHERE DATE_='20170105'
--GROUP BY DATE_,BRANCH
--ORDER BY DATE_ ,SUM(LINENET) 

--ÜRÜN KATEGORİLERİNE GÖRE SATIŞ RAKAMLARI

--SELECT CATEGORY_NAME1 KATEGORY1,BRAND MARKA,SUM(LINENET) FROM
--SALES
--WHERE CATEGORY_NAME1 IS NOT NULL AND CATEGORY_NAME1='GIDA' 
--GROUP BY CATEGORY_NAME1,BRAND
--ORDER BY SUM(LINENET) DESC

--ÜRÜN MARKASINA GÖRE  SATIŞLAR
--SELECT BRAND MARKA,CATEGORY_NAME1,CATEGORY_NAME2,SUM(LINENET) TOPLAMFIYAT
--FROM SALES
--WHERE BRAND IS NOT NULL AND BRAND='ÜLKER '
--GROUP BY BRAND,CATEGORY_NAME1,CATEGORY_NAME2
--ORDER BY BRAND,CATEGORY_NAME1,CATEGORY_NAME2

--MAĞALARIMIZIN MÜŞTERİ SAYISISNI YAZDIRMAK
--SELECT BRANCH MAĞAZAİSMİ,COUNT(DISTINCT CLIENTNAME) MÜŞTERİSAYISI
--FROM SALES
--GROUP BY BRANCH

--SELECT DISTINCT CLIENTNAME FROM SALES WHERE BRANCH='HATAY SUBESİ'
--****DISTINCT BİR KOLONDAKİ TEKRAR EDEN VERİLERİ BİR ADET OLACAK ŞEKİLDE SIRALAR


-- BİR MÜŞTERİNİN GİTTİĞİ MAĞAZA SAYISI
--SELECT CLIENTNAME MÜŞTERİİSMİ,COUNT(DISTINCT BRANCH ) GİTTİĞİMAĞAZASAYISI FROM SALES
--GROUP BY CLIENTNAME
--HAVING COUNT(DISTINCT BRANCH)>10
--SELECT DISTINCT BRANCH FROM SALES 
--WHERE CLIENTNAME='LEVENT ALPEREN'