-- HER BİR KULLANICININ KAÇ TANE ADERSİ VAR ONU LİSTELEYELİM
--SELECT U.USERNAME_ KULLANICIADI,
--U.NAMESURNAME AS ADSOYAD,
--U.EMAIL AS EMAIL,
--U.TELNR1 TELEFON1,
--U.TELNR2 TELEFON2,
--COUNT(A.ID) AS ADRESSAYISI
--FROM USER_ U --TAKMA İSİM ALİAS
--LEFT JOIN ADDRES A ON U.ID=A.USERID
--LEFT JOIN CITY C ON C.ID=A.CITYID
--LEFT JOIN TOWN T ON T.ID=A.TOWNID
--LEFT JOIN DISTRICT D ON D.ID=A.DISTRICTID
----WHERE U.ID=15
--GROUP BY U.USERNAME_ ,
--U.NAMESURNAME,
--U.EMAIL ,
--U.TELNR1 ,
--U.TELNR2 
--HAVING COUNT(A.ID)=3

-- hangi şehirde kaç kullanıcı var
SELECT 
U.USERNAME_ KULLANICIADI,
U.NAMESURNAME AS ADSOYAD,
U.EMAIL AS EMAIL,
U.TELNR1 TELEFON1,
U.TELNR2 TELEFON2,
COUNT(A.ID) AS ADRESSAYISI,COUNT(DISTINCT C.CITY) AS SEHIRSAYISI

FROM USER_ U --TAKMA İSİM ALİAS
LEFT JOIN ADDRES A ON U.ID=A.USERID
LEFT JOIN CITY C ON C.ID=A.CITYID
LEFT JOIN TOWN T ON T.ID=A.TOWNID
LEFT JOIN DISTRICT D ON D.ID=A.DISTRICTID
--WHERE U.ID=15
GROUP BY U.USERNAME_,U.NAMESURNAME,U.EMAIL,
U.TELNR1,U.TELNR2
HAVING COUNT(A.ID)<>COUNT(DISTINCT C.CITY)
--671 TANE KAYDIN AYNI ŞEHİRDE BİRDEN FAZLA KAYDI VARMIŞ

