--CONCAT İKİ VEYA DAHA FAZLA STRİNGİ BİLEŞTİRME
SELECT 'OMER '+'FARUK '+'COLAKOGLU'
SELECT CONCAT('OMER ','FARUK ','COLAKOGLU')
SELECT CONCAT_WS(' ','ZAFER','AVCI')

SELECT 
USERNAME_+' '+PASSWORD_+' '+NAMESURNAME,
CONCAT(USERNAME_,' ',PASSWORD_,' ',NAMESURNAME) AS CONCAT_,
CONCAT_WS(' ',USERNAME_,PASSWORD_,NAMESURNAME) AS CONCATWS
FROM USER_