-- EN ÇOK SATIŞ YAPILAN 10 MÜŞTERİLER
--TOP 10 LİSTESİ
SELECT TOP 10 U.USERNAME_,U.NAMESURNAME,
SUM(BB.TOTAL) AS TOTAL
FROM 
USER_ U
INNER JOIN BASKET B ON B.ID=U.ID
INNER JOIN BASKETDETAIL BB ON BB.BASKETID=B.ID
GROUP BY U.USERNAME_,U.NAMESURNAME
ORDER BY SUM(BB.TOTAL) DESC