--LEFT JOIN
--RIGHT JOIN
--FULL JOIN
SELECT USER_.NAMESURNAME,ADDRES.* FROM USER_
LEFT OUTER JOIN ADDRES ON ADDRES.USERID=USER_.ID
WHERE USER_.ID  IN (100,101,102)


SELECT * FROM USER_ WHERE ID=102

SELECT * FROM ADDRES WHERE USERID IN (100,101,102)
DELETE FROM ADDRES WHERE USERID=102