--LEFT RIGHT LEN
SELECT LEFT('ÖMER ÇOLAKOĞLU',4) --EN BAŞTAKİ 4 KARAKTERİ ALDI
SELECT RIGHT('ÖMER ÇOLAKOĞLU',4) --EN SONDAKI 4 KARAKTERİ ALDI
SELECT LEN('ZAFER AVCI') --UZUNLUK

SELECT LEFT ('ZAFER AVCI',6)
SELECT LEFT('ZAFER AVCI',CHARINDEX(' ','ZAFER AVCI'))
SELECT RIGHT ('ZAFER AVCI',5)
SELECT RIGHT('ZAFER AVCI',LEN('ZAFER AVCI')-CHARINDEX(' ','ZAFER AVCI'))


SELECT LEFT(NAMESURNAME,CHARINDEX(' ',NAMESURNAME)), RIGHT(NAMESURNAME,LEN(NAMESURNAME)-CHARINDEX(' ',NAMESURNAME))
FROM USER_ 