--OCAK 2021 DE BİZDEN ALIŞVERİŞ YAPAN KADIN VE ERKEK MÜŞTERİLER
SELECT U.GENDER CİNSİYET,SUM(BD.TOTAL) AS TOPLAM
FROM USER_ U
INNER JOIN BASKET B ON B.USERID=U.ID
INNER JOIN BASKETDETAIL BD ON BD.BASKETID=B.ID

WHERE B.CREATEDDATE BETWEEN '20220101' AND '20220131' 

GROUP BY U.GENDER