--SUBQUERY İLE MÜŞTERİ BİLGİSİ GETİRME
SELECT U.ID,U.NAMESURNAME,
(SELECT COUNT(*) FROM BASKET WHERE USERID=U.ID) AS BASKETCOUNT,
(SELECT MIN(CREATEDDATE) FROM BASKET WHERE USERID=U.ID) AS FIRSTBASKETDATE,
(SELECT MAX(CREATEDDATE) FROM BASKET WHERE USERID=U.ID) AS LASTBASKETDATE,
(SELECT SUM(TOTAL) FROM BASKETDETAIL WHERE BASKETID IN (SELECT ID FROM BASKET WHERE USERID=U.ID)) AS TOTAL,
(SELECT COUNT(*) FROM BASKETDETAIL WHERE BASKETID IN (SELECT ID FROM BASKET WHERE USERID=U.ID)) AS ITEMCOUNT,
(
SELECT ITEMNAME FROM ITEM WHERE ID IN 
	(
	SELECT TOP 1 ITEMID FROM BASKETDETAIL WHERE BASKETID IN
		(
		SELECT ID FROM BASKET WHERE USERID=U.ID
		)ORDER BY DATE_ DESC 
	)
)AS LASTITEMNAME

FROM USER_ U,BASKET B
WHERE (SELECT COUNT(*) FROM BASKET WHERE USERID=U.ID)>0

--JOIN
SELECT U.ID,U.NAMESURNAME AS ISIMSOYSISIM,COUNT(B.ID) AS BASKETCOUNT,MAX(BD.DATE_) AS LASTBASKETDATE,
MIN(BD.DATE_) AS FIRSTBASKETDATE,SUM(BD.TOTAL) AS TOTAL

FROM USER_ U
INNER JOIN BASKET B ON B.USERID=U.ID
INNER JOIN BASKETDETAIL BD ON BD.BASKETID=B.ID

GROUP BY U.ID,U.NAMESURNAME
ORDER BY U.ID ASC