SELECT 
U.NAMESURNAME ISIMSOYISIM,
U.EMAIL EMAIL,
U.GENDER CINSIYET,
U.BIRTHDATE DOGUMTARIHI,
C.COUNTRY ULKE,
CY.CITY SEHIR,
T.TOWN ILCE,
A.POSTALCODE,
A.ADDRESSTEXT
FROM 
USERS U,ADDRESS A, COUNTRIES C, CITIES CY , TOWNS T

WHERE U.ID=A.USERID AND A.COUNTRYID=C.ID 
AND A.CITYID=CY.ID
AND A.TOWNID=T.ID
AND CY.CITY LIKE 'BURSA'
--AND U.ID=1