SELECT 
C.CITY,COUNT(OD.ID) TOPLAMSIPARIS,SUM(OD.LINETOTAL) TOPLAMTUTAR
FROM ORDERS O

INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
INNER JOIN CITIES C ON C.ID=A.CITYID
INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID


GROUP BY C.CITY,C.ID 

ORDER BY C.CITY ASC