SELECT  
U.USERNAME_ KULLANICIADI,U.NAMESURNAME AS ADSOYAD,CT.CITY SEHIR,T.TOWN ILCE,D.DISTRICT SEMT,
O.ID AS SIPARISID,O.DATE_ TARIH,O.TOTALPRICE TOPLAM,P.DATE_ AS ODEMETARIHI,P.ISOK BANKAONAY,
I.DATE_ FATURATARIHI,I.CARGOFICHENO KARGOTAKIP,ITE.ITEMNAME URUNISMI,ITE.BRAND MARKA,OD.AMOUNT MIKTAR,
OD.LINETOTAL AS SATIRTOPLAM,ITE.UNITPRICE

FROM ORDERS O
INNER JOIN USERS U ON U.ID=O.USERID
INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
INNER JOIN CITIES CT ON CT.ID= A.CITYID
INNER JOIN TOWNS T ON T.ID= A.TOWNID
INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
INNER JOIN INVOICES I ON I.ORDERID=O.ID
INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
INNER JOIN ITEMS ITE ON ITE.ID=OD.ITEMID

WHERE   
O.ID=17342

--U.NAMESURNAME='ZAFER EKİZKAYA'
