SELECT 
DATEPART(MONTH,DATE_) AY,
CASE 
	WHEN PAYMENTTYPE = 1 THEN 'KREDİ KARTI'
	WHEN PAYMENTTYPE = 2 THEN 'BANKA HAVALESİ'
END ODEMETURU_ACIKLAMA,
SUM(PAYMENTTOTAL) AS TOPLAMTUTAR
FROM PAYMENTS

GROUP BY DATEPART(MONTH,DATE_),PAYMENTTYPE
ORDER BY DATEPART(MONTH,DATE_)