
SELECT 
U.ID,U.NAMESURNAME,
AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_)) AS ORTLAMA_TESLIMAT_SURESI,
SUM(O.TOTALPRICE) TOPLAMSIPARIS
FROM ORDERS O
INNER JOIN USERS U ON U.ID=O.USERID
INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
INNER JOIN CITIES CT ON CT.ID= A.CITYID
INNER JOIN TOWNS T ON T.ID= A.TOWNID
INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
INNER JOIN INVOICES I ON I.ORDERID=O.ID



GROUP BY U.ID,U.NAMESURNAME
HAVING AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_))> 20
ORDER BY 4 DESC

