
SELECT  
DATEPART(YEAR,O.DATE_),
CASE 
	WHEN DATEPART(MONTH,O.DATE_)=1 THEN 'OCAK'
	WHEN DATEPART(MONTH,O.DATE_)=2 THEN 'ŞUBAT'
	WHEN DATEPART(MONTH,O.DATE_)=3 THEN 'MART'
	WHEN DATEPART(MONTH,O.DATE_)=5 THEN 'NİSAN'
	WHEN DATEPART(MONTH,O.DATE_)=6 THEN 'MAYIS'
	WHEN DATEPART(MONTH,O.DATE_)=7 THEN 'HAZİRAN'
	WHEN DATEPART(MONTH,O.DATE_)=8 THEN 'TEMMUZ'
	WHEN DATEPART(MONTH,O.DATE_)=9 THEN 'AĞUSTOS'
	WHEN DATEPART(MONTH,O.DATE_)=10 THEN 'EYLÜL'
	WHEN DATEPART(MONTH,O.DATE_)=11 THEN 'EKİM'
	WHEN DATEPART(MONTH,O.DATE_)=12 THEN 'KASIM'
END AYADI, 
DATEPART(YEAR,O.DATE_) YIL,
SUM(OD.LINETOTAL) TOPLAMSIPARIS_TUTAR,
SUM(OD.AMOUNT) TOPLAMSIPARIS_MIKTARI,
COUNT(OD.ID)
FROM ORDERS O
INNER JOIN USERS U ON U.ID=O.USERID
INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
INNER JOIN CITIES CT ON CT.ID= A.CITYID
INNER JOIN TOWNS T ON T.ID= A.TOWNID
INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
INNER JOIN INVOICES I ON I.ORDERID=O.ID
INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
INNER JOIN ITEMS ITE ON ITE.ID=OD.ITEMID


GROUP BY DATEPART(MONTH,O.DATE_),DATEPART(YEAR,O.DATE_)
ORDER BY DATEPART(MONTH,O.DATE_),DATEPART(YEAR,O.DATE_)