SELECT 
U.NAMESURNAME,COUNT(A.ID) AS ADDRESSAYISI,COUNT(DISTINCT C.COUNTRY) AS ULKESAYISI,
COUNT(DISTINCT CY.ID) AS SEHIRSAYISI

FROM 
USERS U,ADDRESS A, COUNTRIES C, CITIES CY , TOWNS T

WHERE U.ID=A.USERID AND A.COUNTRYID=C.ID 
AND A.CITYID=CY.ID
AND A.TOWNID=T.ID
--AND CY.CITY LIKE 'BURSA'
--AND U.ID=1
GROUP BY U.NAMESURNAME
HAVING COUNT(A.ID)>2
