--CONCAT STRING BIRLESTIRME
SELECT 'ZAFER'+' AVCI'
SELECT CONCAT('ZAFER',' ','AVCI',' ','BIRINCI SINIF PC MUH')
SELECT CONCAT_WS('+','ZAFER','AVCI','PC MUH','OGRENCISI')
SELECT CONCAT_WS(' ','OMER','FARUK','COLAKOGLU')
SELECT CONCAT_WS('+',U.NAMESURNAME,U.USERNAME_) FROM USERS U
