--LEFT,RIGHT,LEN
--SELECT RIGHT('ZAFER AVCI',5)
--SELECT LEFT('ZAFER AVCI',5)
--SELECT LEN('ZAFER AVCI')

--SELECT CHARINDEX(' ',U.NAMESURNAME) FROM USERS U
SELECT LEFT(U.NAMESURNAME,CHARINDEX(' ',U.NAMESURNAME)) FROM USERS U
SELECT CONCAT_WS('+',LEFT(U.NAMESURNAME,CHARINDEX(' ',U.NAMESURNAME)),RIGHT(U.NAMESURNAME,(LEN(U.NAMESURNAME)-(CHARINDEX(' ',U.NAMESURNAME)))) )FROM USERS U