SELECT u.NAMESURNAME,

(SELECT TOP 1 A.ADDRESSTEXT FROM ADDRESS A
	WHERE A.USERID=U.ID
	ORDER BY 1 DESC
) AS SONADRES
,
(SELECT TOP 1 A.ADDRESSTEXT FROM ADDRESS A
	WHERE A.USERID=U.ID
	ORDER BY 1 
) AS İLKADRES
FROM USERS U
