SELECT  MAX(TOTALPRICE) ENYUKSEK ,MIN(TOTALPRICE) ENDUSUK,COUNT(TOTALPRICE) TOPLAMSATIS,
SUM(TOTALPRICE) TOPLAM,AVG(TOTALPRICE) AS ORTALAMA  FROM SALES
WHERE CITY='ADANA'

SELECT  MAX(TOTALPRICE) ENYUKSEK ,MIN(TOTALPRICE) ENDUSUK,COUNT(TOTALPRICE) TOPLAMSATIS,
SUM(TOTALPRICE) TOPLAM,AVG(TOTALPRICE) AS ORTALAMA  FROM SALES
WHERE CITY='İSTANBUL'

SELECT TOTALPRICE FROM SALES ORDER BY TOTALPRICE DESC