SELECT SUM(TOTALPRICE) AS TOTAL,CITY,DATE2
FROM SALES WHERE CITY='ANKARA'  
GROUP BY CITY,DATE2
ORDER BY DATE2 

SELECT *
FROM SALES WHERE CITY='ANKARA' AND DATE2='20190101'
ORDER BY DATE_



--UPDATE SALES SET DATE2=CONVERT(DATE,DATE_)
--SELECT CONVERT(DATE,DATE_)
--FROM SALES