SELECT CITY,SUM(TOTALPRICE) AS 'TOPLAM FIYAT',
 COUNT(DISTINCT CUSTOMERNAME) CUSTOMERCOUNT
FROM SALES

--WHERE CITY IN ('HATAY','BOLU','İSTANBUL','İZMİR')
GROUP BY CITY

HAVING SUM(TOTALPRICE) > 40000
AND COUNT(DISTINCT CUSTOMERNAME) > 500

ORDER BY [TOPLAM FIYAT] DESC