
--MÜŞTERİ SAYİSİ
SELECT CITY,COUNT(DISTINCT CUSTOMERNAME) UNIQUECUSTOMER,
COUNT(DISTINCT FICHENO) AS 'FİŞ SAYİSİ',
COUNT( *) AS 'BARKOD SAYISI '
FROM SALES 
WHERE MONTHNAME_='01.OCAK'
GROUP BY CITY
ORDER BY CITY 
