SELECT TOP (1000) [ID]
      ,[CUSTOMERNAME]
      ,[CITY]
      ,[BIRTHDATE]
      ,[DISTRICT]
      ,[GENDEL]
  FROM [BTKETRADE].[dbo].[CUSTOMERS]
INSERT INTO CUSTOMERS
VALUES
('EMRE AVCI','KÜTAHYA','2003-08-12','PAYAS','E')


