--email isim sum(orders)
-- KULLANICILARIN TOPLAM SIPARIS SAYISI

select 
 U.EMAIL MAIL,U.NAMESURNAME,COUNT(O.ID) TOPLAMSIPARISSAYISI,U.ID
from USERS u
 
INNER JOIN ORDERS O ON O.USERID=U.ID

GROUP BY U.EMAIL ,U.NAMESURNAME,U.ID
ORDER BY 4