SELECT 
	IT.CATEGORY1,SUM(OD.LINETOTAL) TOPLAMSIPARIS_TUTARI,
	SUM(OD.AMOUNT) TOPLAMSIARIS_ADEDI,
	SUM(OD.LINETOTAL)/SUM(OD.AMOUNT) ORTALAMABIRIMFIYAT
FROM ADDRESS A 
	INNER JOIN USERS U ON U.ID=A.USERID
	INNER JOIN ORDERS O ON O.ADDRESSID=A.ID 
	INNER JOIN CITIES C ON C.ID=A.CITYID
	INNER JOIN TOWNS T ON T.ID=A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID=O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	INNER JOIN ITEMS IT ON IT.ID=OD.ITEMID

--WHERE IT.CATEGORY1='KOZMETIK'
GROUP BY IT.CATEGORY1
--KIRILIM YAPMAK ICIN CATEGORY1 IN YANINA CATEGORY2 DE LAZIM 
