-- =		 EŞİTTİR
-- <>		 EŞİT DEĞİLDİR
-- >		 BÜYÜKTÜR
-- <		 KÜÇÜKTÜR
-- >=		 BÜYÜK EŞİT
-- <=		 KÜÇÜK EŞİT
-- BETWEEN  ARASINDA
-- LIKE	 İLE BAŞLAR, İLE BİTER,İÇERİR
-- IN		 İÇİNDEDİR
-- NOT LIKE İLE BAŞLAMAZ, İLE BİTMEZ, İÇERMEZ
-- NOT IN   İÇİNDE DEĞİLDİR
SELECT * 
FROM CUSTOMERS C
WHERE C.CITY IN ('KUTAHYA','HATAY') --ŞEHRİ KUTAHYA VE HATAY OLANLAR
WHERE C.CUSTOMERNAME NOT LIKE '%C%'
WHERE C.CUSTOMERNAME LIKE '%C%' --İÇERSİNDE C HARFİ GEÇİYOR
WHERE C.AGE BETWEEN 20 AND 30   
WHERE C.BIRTHDATE BETWEEN '19800101' AND '20020101'
WHERE  C.BIRTHDATE >'20020101'

UPDATE CUSTOMERS 
SET GENDEL='KADIN'
WHERE GENDEL='K'

DELETE FROM CUSTOMERS 
WHERE CUSTOMERNAME='MUSTAFA KARA'