--ŞEHİRLERİN TOPLAM SİPARİŞ SAYISI

select 
C.CITY,COUNT(O.ID) [SEHİRDEKİ TOPLAM SIPARIS],C.ID
from ADDRESS A

INNER JOIN CITIES C ON C.ID=A.CITYID
INNER JOIN ORDERS O ON O.ADDRESSID=A.ID

GROUP  BY C.CITY,C.ID
ORDER BY 2